# Features
features = ['Femal', 'Live', 'Married', 'Saudi', 'Volenteer', 'Contributed', 'Doctor', 'Prince', 'Orphancaring', 'Ministry', 'DoctorTitel', 'Travel', 'Acting', 
'Twin','SulimanCenter','Ehsan','Kawater','Cancer','PoorHouse','Univercity','Operataion','HaveNeckname','MemberAtInstitution',
'Award','VolanteerGiude','Eidz','Mawhobeen','ShiningWorldCompassionAward','Safeerah','Blind',
'Success','Misk','Kurbah','Arafat','ReseachCenter','ENEZA','Faysaliah','isJeddah', 'isRyadah', 'isother']

# Questions
questions = {
  'Femal': 'هل الشخصية أنثى ؟',
  'Live': 'هل الشخصيه على قيد الحياه؟',
  'Married': 'هل الشخصية متزوجة؟',
  'Saudi': 'هل الشخصية ولدت او عاشت في السعودية؟',
  'Volenteer': 'هل الشخصية تمارس العمل التطوعي؟',
  'Contributed': 'هل الشخصية شاركت  في عدد من الجمعيات؟',
  'Doctor': 'هل الشخصية تعمل كطبيب؟',
  'Prince': 'هل الشخصيه من آل سعود؟',
  'Orphancaring': 'هل الشخصية اهتمت بمتابعة الأيتام؟',
  'Ministry': 'هل شغلت الشخصية منصب سفير او وزير سابقا؟',
  'DoctorTitel': 'هل الشخصية تحمل لقب الدكتور؟',
  'Travel': 'هل الشخصية كثيرة السفر للدول الفقيرة؟',
  'Acting': 'هل الشخصية ممثله؟',
  'Twin': 'هل الشخصية شارِكت في عمليات فصل التوائم السيامية؟',
  'SulimanCenter':'هل الشخصيه صاحبة فكرة تأسيس مركز الملك سلمان للإغاثة؟',
  'Ehsan':'هل الشخصية أنشأت موقع إحسان؟',
  'Kawater':'هل الشخصية صاحبة برنامج خواطر؟',  
  'Cancer':'هل الشخصية ناشطة عالمية لها نشاطها المحلي والدولي في مجال سرطان الثدي؟',
  'PoorHouse':'هل الشخصية اهتمت بتأمين الوحدات السكينة للفقراء؟',
  'Univercity':'هل الشخصية افتتحت جامعة الأمير مقرن بن عبد العزيز الأهلية؟',
  'Operataion':'هل الشخصية قامت بإجراء عمليات جراحيات تطوعية؟',
  'HaveNeckname':'هل الشخصية هي التي اطلق عليها غازي القصيبي لقب "شهبندر العمل الاجتماعي؟',
  'MemberAtInstitution':'هل الشخصية عضوة قي جمعية النهضة النسائية الخيرية؟' ,
  'Award':'هل الشخصية مؤسسة لجائزة محمد بن سحيم لحفظ القران والتفوق العلمي؟' ,
  'VolanteerGiude':'هل الشخصية أعدت دليل التطوع للمشاركة في أعمال الإغاثة والخدمات الإسعافية لجمعية الهلال الأحمر السعودي؟',
  'Eidz':'هل الشخصية مديرة برنامج الإيدز والمشرفة على قسم المناعة بوزارة الصحة؟',
  'Mawhobeen':'هل الشخصية شاركت في مؤسسة الملك عبد العزيز ورجاله لرعاية الموهوبين؟',
  'ShiningWorldCompassionAward':'؟Shining World Compassion Award هل الشخصية حصلت على جائزة',
  'Safeerah':'هل الشخصية حصلت على عضوية برنامج سفراء الجامعة لتكون بذلك أول مبتعثة من السعودية وأول سفيره سعودية؟',
  'Blind':'هل الشخصية هي أول عضو كفيف في تاريخ مجلس الشورى؟',
  'Success':'هل الشخصية انشاءت جمعية خيرية قدمت برنامج فرحة النجاح؟',
  'Misk':'هل الشخصية عملت  أمينًا عامًا لمؤسسة محمد بن سلمان “مسك” الخيرية؟',
  'Kurbah':'هل الشخصية دعمت المبادرات المجتمعية الإيجابية كمبادرة لجنة تراحم حملات تفريج كربة؟',
  'Arafat':'هل الشخصية نفذت مشاريع عديده في عرفات؟',
  'ReseachCenter':'هل الشخصية أنشأت معهد فقيه للأبحاث؟',
  'ENEZA':'هل الشخصية مؤسسة للجمعية الخيرية الصالحية بعنيزة التي تقف شامخة تعلم الأجيال؟',
  'Faysaliah':'هل الشخصية رئيسة الجمعية الفيصلية الخيرية النسوية؟',
  'isJeddah': 'هل الشخصية من جدة؟',
  'isRyadah': 'هل الشخصية من الرياض؟',
  'isother': 'هل الشخصية من مدن المملكة أخرى غير جده والرياض؟'
}

# Answers Buttons
answers = {
  'Femal': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Live': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Married': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Saudi': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Volenteer': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Contributed': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Doctor': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Prince': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Orphancaring': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Ministry': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'DoctorTitel': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Travel': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Acting': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Twin': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'SulimanCenter': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Ehsan': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Kawater': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Cancer': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'PoorHouse': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Univercity': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Operataion': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'HaveNeckname': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'MemberAtInstitution': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Award': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'VolanteerGiude': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Eidz': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Mawhobeen': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'ShiningWorldCompassionAward': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Safeerah': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Blind': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Success': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Misk': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Kurbah': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Arafat': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'ReseachCenter': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'ENEZA': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'Faysaliah': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'isJeddah': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'isRyadah': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }],
  'isother': [{ 'title': 'Yes', 'value': 1 }, { 'title': 'No', 'value': 0 }] 
}

# Answers that is String
questionWithComplete = []

# Absolute (Remove train_x item if is not equal)
absoluteFeatures = []